<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>304ccc1b-da28-47be-b758-1d5ab0240380</elementGuidId>
    <imagePath></imagePath>
    <name>span_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[1]/div[1]/div[1]/button[1]/span[1]/span[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.MuiStepLabel-iconContainer.Mui-completed</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'MuiStepLabel-iconContainer Mui-completed MuiStepLabel-alternativeLabel css-a5nipc')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiStepLabel-iconContainer Mui-completed MuiStepLabel-alternativeLabel css-a5nipc</value>
        <webElementGuid>00c628ab-8f91-4715-a033-599f52b47363</webElementGuid>
    </webElementProperties>
</WebElementEntity>