<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f9b2caca-e7fa-4076-8721-85d1d0c45414</elementGuidId>
    <imagePath></imagePath>
    <name>span_object_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[1]/div[1]/div[1]/button[1]/span[1]/span[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.MuiStepLabel-iconContainer.Mui-completed</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'MuiStepLabel-iconContainer Mui-completed MuiStepLabel-alternativeLabel css-a5nipc')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiStepLabel-iconContainer Mui-completed MuiStepLabel-alternativeLabel css-a5nipc</value>
        <webElementGuid>17f65970-83ee-46de-b3ed-82c8b0efafd4</webElementGuid>
    </webElementProperties>
</WebElementEntity>