<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>80003ba3-4917-4f9a-ad63-62b66286587c</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_category_accessories</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/footer[1]/div[1]/div[1]/div[2]/ul[1]/li[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.page-footer-menu__element[href='\/category\/accessories']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'page-footer-menu__element is-link')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>page-footer-menu__element is-link</value>
        <webElementGuid>dcc9aebd-d916-4cbf-ad01-c149ba1ae5bf</webElementGuid>
    </webElementProperties>
</WebElementEntity>