<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c4c42863-9d5e-4c6b-8abf-4d59b12421bc</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/a[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.swiper-slider__next</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'swiper-slider__next swiper-button-disabled')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>swiper-slider__next swiper-button-disabled</value>
        <webElementGuid>17e46ae1-e522-415c-8351-71870fa13e17</webElementGuid>
    </webElementProperties>
</WebElementEntity>