<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b6072e3d-c0fb-40a4-b3f8-a4c7a698c994</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.swiper-slider__prev</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'swiper-slider__prev swiper-button-disabled')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>swiper-slider__prev swiper-button-disabled</value>
        <webElementGuid>0ae5bfd4-515b-48d8-bc0f-3b56edd57f9e</webElementGuid>
    </webElementProperties>
</WebElementEntity>