<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3b1c2269-1ba0-4982-8328-23bf2ac1a725</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_cart</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/header[1]/section[1]/div[1]/div[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.mars-logo-row__at-right .cart-header</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'cart-header cart-header_empty')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>cart-header cart-header_empty</value>
        <webElementGuid>5afd3e33-e33e-4f62-b019-3c1076141ecd</webElementGuid>
    </webElementProperties>
</WebElementEntity>