<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ba975283-4c94-4dd3-92a7-99a52251a55c</elementGuidId>
    <imagePath></imagePath>
    <name>button_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.btn-lg</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'btn btn-action btn-anim btn-lg')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn-action btn-anim btn-lg</value>
        <webElementGuid>209ed249-d598-46de-aa52-c7e0d74d970c</webElementGuid>
    </webElementProperties>
</WebElementEntity>