<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a236ccb6-ebcb-4b6c-9d46-e1f988fc62b6</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[1]/div[1]/div[1]/figure[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.product-gallery__big-img a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>