<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>bda2553e-b700-4c51-ac13-728bf5df5679</elementGuidId>
    <imagePath></imagePath>
    <name>button_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[1]/form[1]/div[4]/div[1]/button[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.category-filters</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'category-filters px-1')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>category-filters px-1</value>
        <webElementGuid>c0b0bb0c-ddb3-4d1a-b16a-c03ef35a35f9</webElementGuid>
    </webElementProperties>
</WebElementEntity>