<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>aa251c65-414a-4469-989e-57e0899f9529</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[2]/div[1]/div[2]/ul[1]/li[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.sort-buttons__element.active .sort-buttons__link</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'sort-buttons__link')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>sort-buttons__link</value>
        <webElementGuid>735ad207-b0f1-4111-b15a-4ecce2e2e4c0</webElementGuid>
    </webElementProperties>
</WebElementEntity>