<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>98dafbd7-f949-4a65-9759-104cd15d7442</elementGuidId>
    <imagePath></imagePath>
    <name>input_object_2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>('//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[1]/form[1]/div[3]/div[1]/label[1]/input[1]',)</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.category-filters</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'category-filters px-1')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>category-filters px-1</value>
        <webElementGuid>7ca49206-408f-4268-8c58-60dd03344fbf</webElementGuid>
    </webElementProperties>
</WebElementEntity>